version: '3.8'

services:
  mydocker:
    build: .
    image: mydocker
    privileged: true
    network_mode: host
    pid: host
    ipc: host
    stdin_open: true
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var:/var:rw
      - /proc:/proc:rw
      - /lib/modules:/lib/modules:ro
      - /etc/resolv.conf:/etc/resolv.conf:ro
      - /run:/run:rw
      - /dev:/dev:rw
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
      - label:disable
    devices:
      - /dev/net/tun
      - /dev/fuse
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
      - kernel.unprivileged_userns_clone=1
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
