version: '3.8'

services:
  mydocker:
    build: .
    privileged: true
    pid: host
    stdin_open: true
    tty: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var:/var:rw
      - /proc:/proc:rw
      - /lib/modules:/lib/modules:ro
    cgroup_parent: host
    cap_add:
      - ALL
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    security_opt:
      - seccomp:unconfined
    network_mode: host
    extra_hosts:
      - "auth.docker.io:44.208.156.194"
      - "registry-1.docker.io:44.193.201.175"
