version: '3.8'

services:
  mydocker:
    build: .
    privileged: true
    pid: host
    stdin_open: true
    tty: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var:/var:rw
      - /proc:/proc:rw
      - /lib/modules:/lib/modules:ro
    cgroup_parent: host
    cap_add:
      - ALL
    network_mode: host
