name: Test Containerization Lab on macOS

on:
  push:
    branches: [ main, master ]
    paths:
      - 'test2/**'
      - '.github/workflows/test-macos.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'test2/**'
      - '.github/workflows/test-macos.yml'

jobs:
  test-macos:
    runs-on: macos-14
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Colima
      run: |
        # Install Homebrew if not already available
        if ! command -v brew &> /dev/null; then
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        fi
        
        # Install Colima
        brew install colima docker qemu
        
        
    - name: Start Colima
      run: |
        # Start Colima with Docker runtime
        LIMACTL_PATH=$(brew --prefix)/bin/limactl
        sudo curl -L -o $LIMACTL_PATH https://github.com/mikekazakov/lima-nohvf/raw/master/limactl && sudo chmod +x $LIMACTL_PATH
        colima start --network-address --arch arm64 --vm-type=qemu
        
        # Wait for Docker to be ready
        echo "Waiting for Docker to start..."
        timeout 60 bash -c 'until docker info > /dev/null 2>&1; do sleep 2; done'
        
        # Verify Docker is working
        docker --version
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Build Docker image
      run: |
        cd test2
        docker build --network=host . -t mydocker
        
    - name: Test basic container functionality
      run: |
        cd test2
        
        # Test that the container can start and run basic commands
        docker run --rm mydocker /bin/sh -c "echo 'Container is working'"
        
        # Test Python environment
        docker run --rm mydocker /bin/sh -c "
          . /venv/bin/activate
          python3 --version
          pip list
        "
        
    - name: Test image extraction functionality
      run: |
        cd test2
        
        # Test the image extraction part of the solution
        docker run --rm --network host mydocker /bin/sh -c "
          cd /w2d2
          . /venv/bin/activate
          python3 -c '
          import sys
          sys.path.append(\"/w2d2\")
          from w2d2_solution import pull_layers
          try:
              pull_layers(\"python:3.11-slim\", \"./test_extracted_python\")
              print(\"SUCCESS: Image extraction test passed\")
          except Exception as e:
              print(f\"Image extraction test failed: {e}\")
              sys.exit(1)
          '
        "
        
    - name: Cleanup
      run: |
        # Stop all running containers
        docker stop $(docker ps -aq) 2>/dev/null || true
        
        # Remove all containers
        docker rm $(docker ps -aq) 2>/dev/null || true
        
        # Remove test images
        docker rmi mydocker 2>/dev/null || true
        
        # Stop Colima
        colima stop || true 