name: Test Containerization Lab on macOS

on:
  push:
    branches: [ main, master ]
    paths:
      - 'test2/**'
      - '.github/workflows/test-macos.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'test2/**'
      - '.github/workflows/test-macos.yml'

jobs:
  test-macos:
    runs-on: macos-14
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install system dependencies
      run: |
        # Install Homebrew if not already available
        if ! command -v brew &> /dev/null; then
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        fi
        
        # Install required packages
        brew install docker docker-compose
        
        # Start Docker Desktop (macOS specific)
        open -a Docker
        
        # Wait for Docker to be ready
        echo "Waiting for Docker to start..."
        timeout 60 bash -c 'until docker info > /dev/null 2>&1; do sleep 2; done'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Build Docker image
      run: |
        cd test2
        docker build --network=host . -t mydocker
        
    - name: Run w2d2_solution.py
      run: |
        cd test2
        
        # Run the solution file and capture output
        docker run --network host --privileged --cgroupns=host \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -v $(pwd):/workspace \
          mydocker /bin/sh -c "
          cd /workspace
          . /venv/bin/activate
          python3 w2d2_solution.py
          "
        
    - name: Cleanup
      run: |
        # Stop all running containers
        docker stop $(docker ps -aq) 2>/dev/null || true
        
        # Remove all containers
        docker rm $(docker ps -aq) 2>/dev/null || true
        
        # Remove test images
        docker rmi mydocker 2>/dev/null || true 